In [1]:
import numpy as np
a=np.array([1,2,3])
b=[4,7,8,12]
print(type(a))
print(a.shape)
print(b)
print(type(b))


<class 'numpy.ndarray'>
(3,)
[4, 7, 8, 12]
<class 'list'>


In [3]:
print(a[0],a[1],a[2])
a[0]=5
print(a)
b=np.array([[1,2,3] , [4,5,6]])
print(b.shape)
print(b[0,0] , b[0,1] , b[1,0])

1 2 3
[5 2 3]
(2, 3)
1 2 4


In [5]:
#numpy functions
import numpy as np
a=np.zeros((2,2))
print(a)

b=np.ones((1,2))
print(b)

c=np.full((2,2), 7)
print(c)

d=np.eye(2)
print(d)

e=np.random.random((2,2))
print(e)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.97028524 0.93301559]
 [0.52602567 0.69176606]]


In [7]:
import numpy as np
np.linspace(2.0, 3.0, num=5, retstep=True)


(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [9]:
import numpy as np
np.linspace(2.0, 3.0, num=5)


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [11]:
import numpy as np
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [13]:
#slicing
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:3]
print(a[0,1])

2


In [35]:
#slicing #f
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[-3:-1,-2:-1]
print(b)


[[3]
 [7]]


In [37]:
#b
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [39]:
#c
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[0:2,1:2]
print(b)

[[2]
 [6]]


In [41]:
#d
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[2:3,0:2]
print(b)

[[ 9 10]]


In [43]:
#e
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:]
print(b)

[[2 3 4]
 [6 7 8]]


In [47]:
import numpy as np
a=np.array([[1,2] , [3,4] ,[5,6]])
print(a[[0,1,2],[0,1,0]])

print(np.array([a[0,0],a[1,1],a[2,0]]))

print(a[0,0],a[1,1])

print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
1 4
[2 2]


In [49]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=np.array([0,2,0,1])
print(a[np.arange(4), b])
a[np.arange(4), b] += 10
print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [51]:
#b00lean array indexing
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)
print (a[bool_idx])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [53]:
#data type
import numpy as np
x=np.array([1,2])
print(x.dtype)
x=np.array([1.0,2.0])
print(x.dtype)
x=np.array([1,2],dtype=np.int64)
print(x.dtype)

int32
float64
int64


In [55]:
#array math
import numpy as np
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [57]:
#transpose of array
import numpy as np  
a= np.arange(6).reshape((2,3))  
print(a)  
b=np.transpose(a)  
print(b)



[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [59]:
#Eigenvalues and Eigenvectors in Python
import numpy as np 
m = np.array([[1, 2], 
              [2, 3]]) 
print("Printing the Original square array:",m) 
w, v = np.linalg.eig(m) 
print("the Eigen values of the given square array:", w) 
print("the eigenvectors of the given square array:",v)

Printing the Original square array: [[1 2]
 [2 3]]
the Eigen values of the given square array: [-0.23606798  4.23606798]
the eigenvectors of the given square array: [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [61]:
import numpy as np 
x = np.array([[1, 2, 3], 
              [2, 3, 4], 
              [4, 5, 6]]) 
print("Printing the Original square array:",x) 
w, v = np.linalg.eig(x) 
print("the Eigen values of the given square array:", w) 
print("the eigenvectors of the given square array:",v)

Printing the Original square array: [[1 2 3]
 [2 3 4]
 [4 5 6]]
the Eigen values of the given square array: [ 1.08309519e+01 -8.30951895e-01 -1.09042184e-16]
the eigenvectors of the given square array: [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]
